### ISSUE TITLE
New ESPHome release (v1.15.x) broke compatibility

### ISSUE THREAD

**Issue by OneArmedBand1t** [rnauber/ESPHomeMatrixLED#8]
Hi,

ESPHomeMatrixLED stopped working with the latest major version update from ESPHome.
It works fine with v1.14.x but won't compile on v1.15.x.

**Relevant errors from log:**
```
...
Compiling .pioenvs/d1_mini_02/lib4d9/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pioenvs/d1_mini_02/lib4d9/ESP8266WiFi/ESP8266WiFiAP.cpp.o
In file included from src/main.cpp:44:0:
src/my_matrixled_display.h:65:8: error: 'void MatrixLedDisplay::draw_absolute_pixel_internal(int, int, int)' marked override, but does not override
   void draw_absolute_pixel_internal(int x, int y, int color) override {
        ^
Compiling .pioenvs/d1_mini_02/lib4d9/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
src/main.cpp: In lambda function:
src/main.cpp:566:52: error: cannot allocate an object of abstract type 'MatrixLedDisplay'
       static auto matrixled = new MatrixLedDisplay();
                                                    ^
In file included from src/main.cpp:44:0:
src/my_matrixled_display.h:30:7: note:   because the following virtual functions are pure within 'MatrixLedDisplay':
 class MatrixLedDisplay : public display::DisplayBuffer {
       ^
In file included from src/esphome.h:15:0,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:305:16: note: 	virtual void esphome::display::DisplayBuffer::draw_absolute_pixel_internal(int, int, esphome::Color)
   virtual void draw_absolute_pixel_internal(int x, int y, Color color) = 0;
                ^
src/main.cpp: In lambda function:
src/main.cpp:583:52: error: cannot allocate an object of abstract type 'MatrixLedDisplay'
       static auto matrixled = new MatrixLedDisplay();
                                                    ^
In file included from src/main.cpp:44:0:
src/my_matrixled_display.h:30:7: note:   since type 'MatrixLedDisplay' has pure virtual functions
 class MatrixLedDisplay : public display::DisplayBuffer {
       ^
Compiling .pioenvs/d1_mini_02/lib4d9/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
*** [.pioenvs/d1_mini_02/src/main.cpp.o] Error 1
========================== [FAILED] Took 7.80 seconds ==========================

```

Really hope you can help fixing it as I just started experimenting with ESPHomeMatrixLED and really like it.

Cheers!

**Comment by rnauber** [comment]
Thanks for reporting! I tried to update the examples and I will test them tomorrow.

**Comment by rnauber** [comment]
It seems to work now. Feel free to reopen, if I am missing something...

![photo_2020-10-12_21-14-00](https://user-images.githubusercontent.com/7414650/95782319-f26e2380-0ccf-11eb-817d-48dd98db668c.jpg)

**Comment by bellboy** [comment]
Happy new year all,
I am getting pretty much the same errors as above from the current code (Jan 2021).
ESPHome V1.15.3
@rnauber Did you get this to work?

> In file included from src/main.cpp:36:0:
src/my_matrixled_scrolling_display.h:280:8: error: 'void MatrixLedScrollingDisplay::draw_absolute_pixel_internal(int, int, esphome::Color)' marked 'override', but does not override

TY!!

**Comment by rnauber** [comment]
Sorry, I can not reproduce your error. Are you sure that you really using the newest version?
What is the output of 
`git diff`
and
`git describe --always`
?

**Comment by bellboy** [comment]
Thanks for the reply.  First look at your H file, I dug/impressed with how streamlined your code is.  So I am convinced I have something setup wrong in ESPHome.

ESPHome V1.15.3  is installed.  Is there a specific ESPHome branch that I should be using?

No diff and my checked out hash is d179f43 which seems to match GH.

For my_matrixled_scrolling_display.h which I placed in my ESPHome custom_components directory.  I see it being included in the ESPHome source.

I don't really know ESPHome that well, but it seems pretty straight forward.

Let me know if I am missing anything.  TY

**Comment by rnauber** [comment]
> Thanks for the reply. First look at your H file, I dug/impressed with how streamlined your code is. 

Thank you very much!

> So I am convinced I have something setup wrong in ESPHome.
> 
> ESPHome V1.15.3 is installed. Is there a specific ESPHome branch that I should be using?

No, master or dev should be fine.

> 
> No diff and my checked out hash is [d179f43](https://github.com/rnauber/ESPHomeMatrixLED/commit/d179f432613726898ff4b485b5454f2a03939766) which seems to match GH.
> 
> For my_matrixled_scrolling_display.h which I placed in my ESPHome custom_components directory. I see it being included in the ESPHome source.

Oh! You do not need to move that file into your ESPHome source. It will be copied to your build dir automatically via the include in your yaml:
```
esphome:
...
  includes:
    - my_matrixled_scrolling_display.h
```
> 
> I don't really know ESPHome that well, but it seems pretty straight forward.
> 
> Let me know if I am missing anything. TY

I am guessing that you are somehow accidentally using the old version of that file. Maybe you can try cleaning the build directory...

**Comment by bellboy** [comment]
I figured it out by stepping through the main.cpp source.  I have another couple of devices that uses a custom OLED display.  The source from the custom components are included if you use them on a device or not. Which confuses me a bit.  I would have thought not having a reference in the yaml would cause them to be ignored/not linked into the source.

Thank you for your help.  I love this project.
